### ISSUE TITLE
Cabbage from Sink (furni_id: 19991)

### ISSUE THREAD

**Issue by JrPandaTTV** [SageSaga/Ace-Hotel-SEA#2]
Should be handitem: water instead of cabbage.

![image](https://user-images.githubusercontent.com/52599134/209349573-dd08a873-c8a4-4f1b-b1b4-3ecf95ee140f.png)

**Comment by SageSaga** [comment]
Please provide the cata id

**Comment by JrPandaTTV** [comment]
Bathroom - 182

**Comment by SageSaga** [comment]
This cabbage thing is actually a troll I think, but we've removed it as the sole purpose is to wash hand, not drink. Closed as fixed.
