### ISSUE TITLE
Unable to activate Aurora Borealis Room BG

### ISSUE THREAD

**Issue by JrPandaTTV** [SageSaga/Ace-Hotel-SEA#3]
![image](https://user-images.githubusercontent.com/52599134/209355700-86c2b6d3-64f5-49fc-9f75-41187aa227a0.png)

**Comment by JrPandaTTV** [comment]
'12 Castle (481)

**Comment by SageSaga** [comment]
I don't think so this can be triggered in Nitro. Therefore closed.
